export const personalInfo = {
  name: "Souhail AIT SAID",
  title: "personalInfo.title",
  email: "souhailaitsaid@gmail.com",
  phone: "+32 470 45 71 66",
  address: "1120, Brussels, Belgium",
  summary: "personalInfo.summary",
};

export const experiences = [
  {
    period: "2024-09 - Present",
    company: "Proxymed",
    role: "experience.roles.lead_engineer",
    location: "Brussels, Belgium",
    projects: "experience.projects.drivebook_invoicing",
    roleDescription: "experience.descriptions.lead_engineer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "Angular",
      "Ionic",
      "RxJS",
      "Git/GitLab",
      "TypeScript",
      "REST",
      "Swagger",
      "Kubernetes",
      "Docker",
      "MapStruct",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2021-02 - 2024-08",
    company: "Engie Electrabel M&S",
    role: "experience.roles.full_stack_engineer",
    location: "Brussels, Belgium",
    projects: "experience.projects.b2b_b2c_apis",
    roleDescription: "experience.descriptions.full_stack_engineer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "VueJs",
      "Angular",
      "RxJS",
      "Git",
      "Sonarqube",
      "TypeScript",
      "SOAP/REST",
      "Swagger",
      "Azure DevOps",
      "Kubernetes",
      "Docker",
      "Maven",
      "JUnit",
      "DDD",
      "EDA",
    ],
  },
  {
    period: "2019-11 - 2021-01",
    company: "SPF Finance/Justice",
    role: "experience.roles.lead_full_stack_engineer",
    location: "Brussels, Belgium",
    projects: "experience.projects.legal_documents_api",
    roleDescription: "experience.descriptions.lead_full_stack_engineer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "JEE",
      "Wildfly",
      "JSF/PrimeFaces",
      "Angular",
      "TypeScript",
      "RxJS",
      "Docker",
      "GitLab",
      "Kubernetes",
      "Sonarqube",
      "IBM DB2",
      "Oracle",
      "Swagger",
      "REST",
      "Maven",
      "JUnit",
      "DDD",
      "EDA",
    ],
  },
  {
    period: "2019-02 - 2019-11",
    company: "VTS-Scheldt",
    role: "experience.roles.full_stack_developer",
    location: "Brussels, Belgium",
    projects: "experience.projects.weather_partner",
    roleDescription: "experience.descriptions.weather_developer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "JEE",
      "Jboss",
      "Oracle",
      "REST",
      "Angular",
      "TypeScript",
      "RxJS",
      "Bootstrap",
      "Swagger",
      "Jenkins",
      "Maven",
      "JUnit",
      "DDD",
    ],
  },
  {
    period: "2018-03 - 2019-01",
    company: "European Parliament",
    role: "experience.roles.lead_full_stack_engineer",
    location: "Brussels, Belgium",
    projects: "experience.projects.election_result",
    roleDescription: "experience.descriptions.election_engineer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "SQL Server",
      "REST",
      "Angular",
      "TypeScript",
      "RxJS",
      "Bootstrap",
      "Swagger",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2017-10 - 2018-02",
    company: "Total Energies",
    role: "experience.roles.software_engineer",
    location: "Rabat, Morocco",
    projects: "experience.projects.card_processor",
    roleDescription: "experience.descriptions.software_engineer_desc",
    technologies: [
      "Java",
      "Hibernate",
      "Spring Framework",
      "Oracle Database",
      "Struts",
      "JSP",
      "SOAP/REST",
      "Jenkins",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2016-07 - 2017-09",
    company: "Engie Electrabel M&S",
    role: "experience.roles.software_engineer",
    location: "Rabat, Morocco",
    projects: "experience.projects.credit_management",
    roleDescription: "experience.descriptions.credit_engineer_desc",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "TFS",
      "Sonarqube",
      "SOAP/REST",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2015-04 - 2016-06",
    company: "Crédit Agricole L&F",
    role: "experience.roles.software_engineer",
    location: "Rabat, Morocco",
    projects: "experience.projects.credit_management",
    roleDescription: "experience.descriptions.credit_engineer_desc",
    technologies: [
      "Java",
      "JPA/Hibernate",
      "Spring",
      "Spring MVC",
      "Spring batch",
      "Thymeleaf",
      "JSP/JSTL",
      "Struts",
      "JMS",
      "SOAP/REST",
      "AngularJS",
      "Jenkins",
      "Maven",
      "JUnit",
      "Bootstrap",
      "MySQL",
      "Oracle",
      "Maven",
    ],
  },
];

export const education = [
  {
    period: "2010 - 2015",
    degree: "education.degrees.computer_systems",
    school: "EMSI Marrakech",
  },
];

export const skills = {
  technical: [
    "Java / Spring boot",
    "SOAP / Rest API",
    "JPA / Hibernate / SQL",
    "Kafka",
    "Kubernetes / Docker",
    "Angular/ VueJs / Ionic",
    "Agile - Scrum",
    "Databases",
    "Maven",
  ],
  methodologies: [
    "Agile Development",
    "Scrum Framework",
    "Test-Driven Development",
    "Domain-Driven Design",
    "Event-Driven Architecture",
    "Microservices Architecture",
    "DevOps Practices",
    "Continuous Integration",
  ],
  tools: [
    "Git / GitLab / GitHub",
    "Docker / Kubernetes",
    "Jenkins / Azure DevOps",
    "SonarQube",
    "IntelliJ IDEA",
    "Visual Studio Code",
    "Postman / Swagger",
    "JIRA / Confluence",
  ],
};

export const languages = [
  {
    name: "languages.english",
    level: "languages.levels.bilingual",
  },
  {
    name: "languages.french",
    level: "languages.levels.native",
  },
  {
    name: "languages.dutch",
    level: "languages.levels.novice",
  },
];
