import { Education, Experience } from "./components/cv.component";

export const personalInfo = {
  name: "Souhail AIT SAID",
  title: "cv.title",
  phone: "+32 470 45 71 66",
  email: "Souhailaitsaid@gmail.com",
  address: "1120, Brussels, Belgium",
  summary: "cv.summary",
};

export const experiences: Experience[] = [
  {
    period: "2024-09 - ongoing",
    company: "Proxymed",
    role: "cv.experiences.proxymed.role",
    location: "Brussels, Belgium",
    projects: "cv.experiences.proxymed.projects",
    roleDescription: "cv.experiences.proxymed.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "Angular",
      "Ionic",
      "RxJS",
      "Git/GitLab",
      "TypeScript",
      "REST",
      "Swagger",
      "Kubernetes",
      "Docker",
      "OpenShift",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2021-02 - 2024-08",
    company: "Engie Electrabel M&S",
    role: "cv.experiences.engie.role",
    location: "Brussels, Belgium",
    projects: "cv.experiences.engie.projects",
    roleDescription: "cv.experiences.engie.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "VueJs",
      "Angular",
      "RxJS",
      "Git",
      "Sonarqube",
      "TypeScript",
      "SOAP/REST",
      "Swagger",
      "Azure DevOps",
      "Kubernetes",
      "Docker",
      "Maven",
      "JUnit",
      "DDD",
      "EDA",
    ],
  },
  {
    period: "2019-11 - 2021-01",
    company: "SPF Finance/Justice",
    role: "cv.experiences.spf.role",
    location: "Brussels, Belgium",
    projects: "cv.experiences.spf.projects",
    roleDescription: "cv.experiences.spf.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "JEE",
      "Wildfly",
      "JSF/Primefaces",
      "Angular",
      "TypeScript",
      "RxJS",
      "Docker",
      "Gitlab",
      "Kubernetes",
      "Sonarqube",
      "IBM DB2",
      "Oracle",
      "Swagger",
      "REST",
      "Maven",
      "JUnit",
      "DDD",
      "EDA",
    ],
  },
  {
    period: "2019-02 - 2019-11",
    company: "VTS-Scheldt",
    role: "cv.experiences.vts.role",
    location: "Brussels, Belgium",
    projects: "cv.experiences.vts.projects",
    roleDescription: "cv.experiences.vts.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "JEE",
      "Jboss",
      "Oracle",
      "REST",
      "Angular",
      "TypeScript",
      "RxJs",
      "Bootstrap",
      "Swagger",
      "Jenkins",
      "Maven",
      "JUnit",
      "DDD",
    ],
  },
  {
    period: "2018-03 - 2019-01",
    company: "European Parliament",
    role: "cv.experiences.parliament.role",
    location: "Brussels, Belgium",
    projects: "cv.experiences.parliament.projects",
    roleDescription: "cv.experiences.parliament.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "SQL Server",
      "REST",
      "Angular",
      "TypeScript",
      "RxJS",
      "Bootstrap",
      "Swagger",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2017-10 - 2018-02",
    company: "Total Energies",
    role: "cv.experiences.total.role",
    location: "Rabat, Morocco",
    projects: "cv.experiences.total.projects",
    roleDescription: "cv.experiences.total.description",
    technologies: [
      "Java",
      "Hibernate",
      "Spring Framework",
      "Oracle Database",
      "Struts",
      "JSP",
      "SOAP/REST",
      "Jenkins",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2016-07 - 2017-09",
    company: "Engie Electrabel M&S",
    role: "cv.experiences.engie_morocco.role",
    location: "Rabat, Morocco",
    projects: "cv.experiences.engie_morocco.projects",
    roleDescription: "cv.experiences.engie_morocco.description",
    technologies: [
      "Java/SpringBoot",
      "Hibernate/JPA",
      "TFS",
      "Sonarqube",
      "SOAP/REST",
      "Maven",
      "JUnit",
    ],
  },
  {
    period: "2015-04 - 2016-06",
    company: "Crédit Agricole L&F",
    role: "cv.experiences.credit_agricole.role",
    location: "Rabat, Morocco",
    projects: "cv.experiences.credit_agricole.projects",
    roleDescription: "cv.experiences.credit_agricole.description",
    technologies: [
      "Java",
      "JPA/Hibernate",
      "Spring",
      "Spring MVC",
      "Spring batch",
      "Thymleaf",
      "JSP/JSTL",
      "Struts",
      "JMS",
      "SOAP/REST",
      "AngularJS",
      "Jenkins",
      "Maven",
      "JUnit",
      "Bootstrap",
      "MySQL",
      "Oracle",
      "Maven",
    ],
  },
];

export const education: Education[] = [
  {
    period: "2010 - 2015",
    degree: "cv.education.degree",
    school: "EMSI Marrakech",
  },
];

export const skills = {
  technical: [
    "Java / Spring boot",
    "Angular/ VueJs / Ionic",
    "JPA / Hibernate / SQL",
    "SOAP / Rest API",
    "Kubernetes / Docker",
    "Kafka",
  ],
  methodologies: ["Agile - Scrum", "DDD", "EDA"],
  tools: ["Maven", "Git/GitLab", "Jenkins", "Azure DevOps", "Sonarqube"],
};

export const languages = [
  { name: "cv.languages.english", level: "cv.languages.bilingual" },
  { name: "cv.languages.french", level: "cv.languages.native" },
  { name: "cv.languages.dutch", level: "cv.languages.novice" },
];
